export enum ANIMATION_KEY {
  BOX = 'box',
  RAM_ATTACK = 'Ram Attack',
  RAM_DASH = 'Ram Dash',
  RAM_DIZZY = 'Ram Dizzy',
  RAM_FAINT = 'Ram Faint',
  RAM_FALL = 'Ram Fall',
  RAM_FLY = 'Ram Fly',
  RAM_HURT = 'Ram Hurt',
  RAM_IDLE = 'Ram Idle',
  RAM_JUMP = 'Ram Jump',
  RAM_JUMP_UP = 'Ram Jump Up',
  RAM_LANDING = 'Ram Landing',
  RAM_RUN = 'Ram Run',
  RAM_TAKEOFF_RUN = 'Ram Takeoff Run',
  RED_STARS = 'red-stars',
  WHITE_STARS = 'white-stars',
  YELLOW_STARS = 'yellow-stars',
};
